### Listar filmes
GET http://localhost:3001

### Buscar filmes
GET http://localhost:3001/filme/O Banqueiro

### Adicionar aos favoritos
POST http://localhost:3001/favoritos/5
Content-Type: application/json

{
    "titulo" : "Garota Mimada"
}

# {
#     "titulo": "A Proposta"
# }

### Deletar
DELETE http://localhost:3001/Garota Mimada

### Deletar dos favoritos
DELETE http://localhost:3000/2/O Banqueiro

### Cadastrar filme
POST http://localhost:3001/filme
Content-Type: application/json


# {
#     "titulo": "A Proposta",
#     "genero": "Comédia Romântica",
#     "ano": 2009,
#     "estrelas" : 10

# }

{
   "titulo": "Garota Mimada",
   "genero": "Comédia Romântica",
   "ano": 2008,
   "estrelas" : 8
}

# {

#     "titulo": "Viagem 2: A Ilha Misteriosa",
#     "genero": "Ficção Científica",
#     "ano": 2012,
#    "estrelas" : 8
    
# }

# {
#     "titulo" : "O Banqueiro",
#     "genero" : "Drama",
#     "ano" : 2020,
#    "estrelas" : 9
# }



   